name: 'Get and cache dependencies'
description: 'Get the dependencies and cache them'
inputs:
  caching-on:
    description: 'Should caching be used?'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: 'Cache was used successfully.'
    value: ${{ steps.install-deps.outputs.cache-flag }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching-on == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching-on != 'true'
      # just for demo, mirror the input value to the output
      run: |
        npm ci
        echo "cache-flag='${{ inputs.caching-on }}'" >> $GITHUB_OUTPUT
      shell: bash