name: Matrix Demo
# on: push
on: workflow_dispatch
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        # all permutations will be used
        operating-system: [ubuntu-latest, windows-latest]
        node-version: [12, 14, 16]
        # the specific combination will be used in addition to above
        include:
          - operating-system: ubuntu-latest
            node-version: 18
        # the specific combination will be excluded from permutations
        exclude:
          - operating-system: windows-latest
            node-version: 12
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build


      