name: Matrix Conditional
on:
  push:
    paths:
      - 'dummy/**'
      - '.github/workflows/07-matrix-conditional.yml'

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      pde-envs: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            'dummy/**'
          separator: ','
          since_last_remote_commit: true

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "All changed files: $ALL_CHANGED_FILES"
          # for file in ${ALL_CHANGED_FILES}; do
          #   echo "$file was changed"
          # done
      
      - name: Set matrix array
        id: set-matrix
        run: |
          ALL_CHANGED_FILES_ARRAY=(${ALL_CHANGED_FILES//,/ })
          echo "matrix=${ALL_CHANGED_FILES_ARRAY[@]}" >> "$GITHUB_OUTPUT"

  deploy-to-env:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      matrix:
        pde_env: ${{ needs.define-matrix.outputs.pde-envs }}
        # env: [
        #   dev: {PDE_ENV: dev, DATA_FILE: '${{ github.workspace }}/dummy/foo_dev.txt'},
        #   test: {PDE_ENV: test, DATA_FILE: '${{ github.workspace }}/dummy/foo_test.txt'},
        # ]
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo env
        run: |
          echo "PDE_ENV=${{ matrix.pde_env }}"
