name: Matrix Conditional
on:
  push:
    paths:
      - 'dummy/**'
      - '.github/workflows/07-matrix-conditional.yml'

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      data-files: ${{ steps.set-matrix.outputs.data-files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          since_last_remote_commit: true
          separator: ','
          files: |
            dummy/**

      - name: Set matrix array
        id: set-matrix
        env:
          ALL_MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
        run: |
          MODIFIED_FILES_JSON=$(echo "[\"${ALL_MODIFIED_FILES//,/\",\"}\"]")
          echo "data-files=$MODIFIED_FILES_JSON" >> $GITHUB_OUTPUT
          echo $MODIFIED_FILES_JSON

  deploy-to-env:
    runs-on: ubuntu-latest
    needs: define-matrix
    continue-on-error: true
    strategy:
      matrix:
        data_file: ${{ fromJson(needs.define-matrix.outputs.data-files) }}

    env:
      GHA_ENV: >
        ${{ 
          matrix.data_file == 'dummy/foo_dev.txt' && 'dev' || 
          matrix.data_file == 'dummy/foo_test.txt' && 'test' || 
          'unknown' 
        }}
    
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo env
        run: |
          echo "Data file: ${{ matrix.data_file }}"
          echo "${{ env.GHA_ENV }}"