name: 07 Reusable workflow
# runs when called by another workflow
on: 
  workflow_call:
    # specify inputs expected to be received
    inputs:
      artifact-name:
        description: The name of deployable artifact
        type: string
        required: false
        default: dist
    outputs:
      result:
        description: The result of the deployment
        # references output defined in the job below
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: true
    
jobs:
  deploy:
    outputs:
      # references the output defined in the steps below
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          # use the input var
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls 
      - name: Output info
        run: echo "Deploying & uploading..."
      - name: Set result outputs
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT