name: 07 Reusable workflow
# runs when called by another workflow
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output info
        run: echo "Deploying & uploading..."